FROM balenalib/raspberrypi3-openjdk:8-jdk
MAINTAINER knaus thomas
COPY target/buderus-0.0.4-SNAPSHOT.jar /opt/spring-cloud/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/spring-cloud/lib/buderus-0.0.4-SNAPSHOT.jar"]
EXPOSE 8083